# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_ChupAnh.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(940, 476)
        self.labelCamera = QtWidgets.QLabel(Form)
        self.labelCamera.setGeometry(QtCore.QRect(30, 30, 431, 411))
        self.labelCamera.setText("")
        self.labelCamera.setScaledContents(True)
        self.labelCamera.setObjectName("labelCamera")
        self.txtTenNguoiMoi = QtWidgets.QLineEdit(Form)
        self.txtTenNguoiMoi.setGeometry(QtCore.QRect(590, 60, 271, 31))
        self.txtTenNguoiMoi.setObjectName("txtTenNguoiMoi")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(590, 30, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btnChupAnh = QtWidgets.QPushButton(Form)
        self.btnChupAnh.setGeometry(QtCore.QRect(690, 170, 81, 41))
        self.btnChupAnh.setObjectName("btnChupAnh")
        self.btnDongY = QtWidgets.QPushButton(Form)
        self.btnDongY.setGeometry(QtCore.QRect(600, 220, 81, 41))
        self.btnDongY.setObjectName("btnDongY")
        self.btnChupLai = QtWidgets.QPushButton(Form)
        self.btnChupLai.setGeometry(QtCore.QRect(780, 220, 81, 41))
        self.btnChupLai.setObjectName("btnChupLai")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(650, 100, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.labelTookPhoto = QtWidgets.QLabel(Form)
        self.labelTookPhoto.setGeometry(QtCore.QRect(650, 130, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelTookPhoto.setFont(font)
        self.labelTookPhoto.setObjectName("labelTookPhoto")
        self.btnReset = QtWidgets.QPushButton(Form)
        self.btnReset.setGeometry(QtCore.QRect(600, 300, 81, 41))
        self.btnReset.setObjectName("btnReset")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(580, 440, 311, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.btnHoanTat = QtWidgets.QPushButton(Form)
        self.btnHoanTat.setGeometry(QtCore.QRect(660, 370, 141, 41))
        self.btnHoanTat.setObjectName("btnHoanTat")
        self.btnQuayLai = QtWidgets.QPushButton(Form)
        self.btnQuayLai.setGeometry(QtCore.QRect(780, 300, 81, 41))
        self.btnQuayLai.setObjectName("btnQuayLai")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Nhập tên của bạn:"))
        self.btnChupAnh.setText(_translate("Form", "Chụp ảnh"))
        self.btnDongY.setText(_translate("Form", "Đồng ý"))
        self.btnChupLai.setText(_translate("Form", "Chụp lại"))
        self.label_2.setText(_translate("Form", "Yêu cầu chụp: 8 ảnh "))
        self.labelTookPhoto.setText(_translate("Form", "Đang tải..."))
        self.btnReset.setText(_translate("Form", "Reset"))
        self.label_3.setText(_translate("Form", "Hướng dẫn: Đảm bảo đủ sáng, không che mặt."))
        self.btnHoanTat.setText(_translate("Form", "Hoàn tất"))
        self.btnQuayLai.setText(_translate("Form", "Quay lại"))
